spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DBNAME}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${POSTGRES_SCHEMA}
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0
    schemas: ${POSTGRES_SCHEMA}
  
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    
  web:
    locale: ru_RU
    locale-resolver: fixed

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.example: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
